uswds_blb_configuration.admin_config:
  title: 'USWDS Layout Builder'
  route_name: entity.uswds_breakpoint.collection
  parent: system.admin_config_content
  description: 'Manage USWDS Layout Builder Settings.'
  weight: 10
