name: USWDS Layout Builder Configuration
type: module
description: Configuration for using USWDS in layout builder.
core_version_requirement: ^9 || ^10
configure: uswds_blb_configuration.admin_config
package: 'Layout Builder'
dependencies:
  - drupal:layout_builder
  - drupal:media_library
  - media_library_form_element:media_library_form_element

# Information added by Drupal.org packaging script on 2023-08-30
version: '3.0.0'
project: 'uswds_blb_configuration'
datestamp: 1693408386
